### ISSUE TITLE
License checklist

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningfulR#41] opened 2021-03-17 20:00 UTC
rubric={reasoning:10}

Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly dicussed.

**Comment by mikelynch416** [comment] 2021-03-17 22:09
Here are some considerations for the common open source licences.

**MIT**:
- MIT is one of the most permissive free software licenses. Basically, you can do whatever you want with software licensed under the MIT license - only if you add a copy of the original MIT license and copyright notice to it. 

**GPL**: 
- GPL is a copyleft license. This means that any software that is written based on any GPL component must be released as open source. The result is that any software that uses any GPL open source component (regardless of its percentage in the entire code) is required to release its full source code and all of the rights to modify and distribute the entire code.

**Ms-PL**:  
- free to reproduce and distribute original or derivative works of any software licensed under the Ms-PL license. However, you may not use any contributors' name, logo, or trademarks when you do so. 
- The Ms-PL protects the authors by explicitly not offering any express warranties or guarantees for using your code, so the author is not liable if the code doesn’t work well in some cases.
- When you distribute software (or its portion) under the Ms-PL, you’re not required to distribute its source code. However, you’re required to retain all copyright, patent, trademark, and attribution notices that are originally present in the software.
- if you distribute any portion of the software in its source code form, you may do so only under the Ms-PL by including a complete copy of this license with your distribution. 
- If you distribute any portion of the software in its compiled or object code form, you may only do so under any other license that complies with the Ms-PL.

**CDDL**:
- You’re free to reproduce and distribute any original or derivative works of any software licensed under the CDDL. However, you must not remove or make any changes to any copyright, patent or trademark notices contained in the software. You must also retain any notices of licensing or any descriptive text giving attribution to any contributor or the initial developer.
- When you distribute your software in an executable form (any form other than source code), you are required to make the source code available as well under the CDDL. The executable form may be released under the CDDL or any CDDL compatible licenses.
- The source code that you have to make available includes your contributions as long as they are an addition to, deletion from or modification of the contents of a file containing the original software – or new files that contain parts of the original program. That means that if your additions are made in separate and independent files that do not contain the original code, you do not have to release it under the CDDL. 
- In addition, you must include a copy of the CDDL with any source code that you distribute. For each modification that you make, you must identify yourself as the modifier by including a notice in your modified files.

**EPL**: 
- The EPL license is a copyleft license. If you modify an EPL’ed component and distribute it in the source code form as part of your program, you’re required to disclose the modified code under the EPL. If you distribute such a program in its object code form, you’re required to state that the source code can be made available to the recipient upon request. You’re also required to share the method for requesting the source code.
- ‘merely interfacing or interoperating’ with an Eclipse plugin does not make your code a derivative work of the plugin.
- If you redistribute a program with an EPL component, you are obligated to include the full license text and the copyrights.
- The EPL protects the author from possible lawsuits or damages caused if a company used his/her component in a commercial product. It also offers a patent grant.

**Apache**: 
- You can freely use, modify, distribute and sell a software licensed under the Apache License without worrying about the use of software: personal, internal or commercial.
- This license explicitly grants rights to users that can be applied to both copyrights and patents, unlike other permissive licenses that are applicable only to copyrights and not patents. The rights given are perpetual, worldwide, irrevocable, but also non-exclusive — so you can use the licensed work, and so can anyone else.
- If you redistribute software with any Apache licensed components, you must include a copy of the license, provide a clear Apache License attribution, and add modification notices to all the files that you modify.
- You can choose to release the modified or derived products under different licenses, the unmodified parts of the software, however, must retain the Apache License, and you cannot name your modified version in any way that suggests that the final product is endorsed or created by the ASF.
-  Since the Apache License doesn’t require you to release the modified code under the same license, you can choose to add specific license terms and conditions that govern how others use, reproduce, or distribute your modified code.

**Comment by mikelynch416** [comment] 2021-03-17 22:11
We are currently licensing both projects under MIT license but I am leaning towards switching to either GPL, EPL or Apache since these seem to best fit the intent of this project. Let me know if you guys have any thoughts/preferences.

**Comment by sbabicki** [comment] 2021-03-18 18:14
GPL and EPL seem a bit more strict than necessary, IMO. If people make modifications I don't care about being notified. 
Leaving the license as MIT seems fine with me based on https://choosealicense.com/
But I'd also be fine with Apache. It seems like it's basically just a more wordy and strictly enforced version of MIT?

What do you guys think?

**Comment by trevorki** [comment] 2021-03-19 01:45
I think that MIT seems an appropriate choice for us... why not be permissive? There are so many kmeans implementations out there that I'm not worried if anyone does anything with ours. If anyone has strong feelings about another license then I'm all ears, but in the absence of that I'm happy to stick with MIT.

**Comment by mikelynch416** [comment] 2021-03-19 19:19
I guess I just liked the idea of the patent license and retaliation clause in the Apache license, which is there to prevent patents (including patent trolls) from encumbering the software project. However, since the project is coming to an end and it doesn't seem like that will be an issue, I am happy to keep the MIT license as that one also covers all our bases.

As it seems there is consensus to keep the MIT license, I'll close out this issue and mark the license question as resolved. Thanks for your inputs!

**Comment by HazelJJJ** [comment] 2021-03-19 21:34
I think both MIT and GPL are suitable for our project. GPL is a bit strict but I think what we did in the project fits its requirements. We may keep it as open source and let other people to contribute or modify to our code to make them better. But it seems like we will not revisit our project very often in the future, and MIT has pretty loose rules, so keeping MIT seems like a good choice.

**Closed as completed** 2021-03-19 23:50 UTC
